set -g default-shell pwsh
set -g history-limit 10000
set -g focus-events on
set -g claude-code-fix-tty on

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g escape-time 0
set -g repeat-time 200

set -g mouse on
set -g mouse-selection off
set -g scroll-enter-copy-mode on
set -g set-clipboard on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g automatic-rename on
set -g aggressive-resize off
set -g alternate-screen on
