# WSL2 Configuration
# Applied to /etc/wsl.conf inside the WSL2 virtual machine

[automount]
options = "metadata,umask=22,fmask=11"
mountFsTab = true

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
appendWindowsPath = true

[user]
default = root

[boot]
systemd = true
