name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install PSScriptAnalyzer
        run: |
          if (-not (Get-Module -ListAvailable -Name PSScriptAnalyzer)) {
            Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck -AllowClobber
          }

      - name: Run Lint
        run: |
          # Check Scripts for errors
          $Results = @(Get-ChildItem -Path Scripts -File -Recurse -Include *.ps1, *.psm1 | Invoke-ScriptAnalyzer)
          if ($Results | Where-Object -FilterScript {($_.Severity -eq "Error") -or ($_.Severity -eq "ParseError")})
          {
            Write-Verbose -Message "Found script issue" -Verbose

            $Results | Where-Object -FilterScript {($_.Severity -eq "Error") -or ($_.Severity -eq "ParseError")} | ForEach-Object -Process {
              [PSCustomObject]@{
                Line    = $_.Line
                Message = $_.Message
                Path    = $_.ScriptPath
              }
            } | Format-Table -AutoSize -Wrap

            # Exit with a non-zero status to fail the job
            exit 1
          }

      - name: Check PSD1 validity
        run: |
          Get-ChildItem -Path Scripts -File -Filter *.psd1 -Recurse | ForEach-Object -Process {
              $File = $_.FullName

              try
              {
                  # Basic syntax check for PSD1 files
                  $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content -Path $File -Raw), [ref]$null)
              }
              catch
              {
                  Write-Verbose -Message "PSD1 parse error: $File - $_" -Verbose
                  # Exit with a non-zero status to fail the job
                  exit 1
              }
          }

      - name: Check YAML validity
        run: |
          Get-ChildItem -Path . -File -Filter *.yml -Recurse | Where-Object { $_.FullName -notmatch 'node_modules|\.git' } | ForEach-Object -Process {
              $File = $_.FullName
              try
              {
                  # Basic YAML check
                  Get-Content -Path $File | ConvertFrom-Yaml -ErrorAction Stop | Out-Null
              }
              catch
              {
                  Write-Verbose -Message "YAML parse error: $File - $_" -Verbose
              }
          }
